version: "2.4"

services:
        db:
                image: mariadb:latest
                container_name: mariadb
                volumes:
                        - /home/shyeon/workspace/mysql/_dbdump:/var/lib/mysql
                environment:
                        - MYSQL_DATABASE=sparklab
                        - MYSQL_ROOT_PASSWORD=9838
                ports:
                        - "3306:3306"
                        - "4040:4040"
                        - "4041:4041"
                healthcheck:
                        test: mysql -p9838 -Dsparklab -e "SHOW DATABASES"
                        interval: 3s
                        timeout: 1s
                        retries: 3

        web:
                #                build:
                #                        context: .
                #                        dockerfile: ./Dockerfile
                image: dream2globe/my-spark-env
                container_name: mysparklab
                volumes:
                        - ~/workspace/python/SparkDefinitiveGuide:/home/jovyan/work
                ports:
                        - "8888:8888"
                          #                command:
                          #                        - python
                          #                        - app.py
                depends_on:
                        db:
                                condition: service_healthy
