version: "2.4"

services:
        db:
                image: mariadb:latest
                container_name: mariadb_sia
                volumes:
                        - /home/shyeon4win/workspace/mysql:/var/lib/mysql
                environment:
                        - MYSQL_DATABASE=sparklab
                        - MYSQL_ROOT_PASSWORD=9838
                ports:
                        - "3306:3306"
                healthcheck:
                        test: mysql -p9838 -Dsparklab -e "SHOW DATABASES"
                        interval: 3s
                        timeout: 1s
                        retries: 3

        spark:
                image: dream2globe/my-spark-env
                container_name: mysparklab_sia
                volumes:
                        - /home/shyeon4win/workspace/spark/SparkInAction:/home/jovyan/work
                ports:
                        - "8888:8888"
                        - "4040:4040"
                        - "4041:4041"
                depends_on:
                        db:
                                condition: service_healthy
